services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'yourStrong(!)Password' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    container_name: migrator
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - SQL_SERVER_CONNECTION_STRING=Server=sqlserver;Database=Database;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True
    restart: "no"
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      migrator:
        condition: service_completed_successfully
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Api__SqlServerConnectionString=Server=sqlserver;Database=Database;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True
      - Api__Url=http://0.0.0.0:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge